from .new_game import new_Game_page
from .game_modes.easy_mode import easy_Mode
from .start_Mode.easy_game import easy_Game
from .game_modes.hard_mode import hard_Mode
from .start_Mode.hard_game import hard_Game
from .start_Mode.state import State
from .start_Mode import style
from .start_Mode import list_names
from .start_Mode.personajeRonadom import personajeRandom
from .start_Mode.ComprobarCaracteristicas import buscar_caracteristicas
from .start_Mode.ComprobarCaracteristicas import tiene_caracteristica
